### ISSUE TITLE
Testing without Batteries

### ISSUE THREAD

**Issue by lustoerk** [Freenove/Freenove_4WD_Smart_Car_Kit_for_Raspberry_Pi#1]
I'm now at page 55 of the guide and it says "the car must be equipped with batteries", but i can't see why. Would it harm the device if i push both power switches now?

**Comment by ZiJace** [comment]
The equipment will not be damaged, because the test needs to supply power to the motor,servo and other equipment,so the battery needs to be installed.

**Comment by ZiJace** [comment]
@lucky01001 The equipment will not be damaged, because the test needs to supply power to the motor,servo and other equipment,so the battery needs to be installed

**Comment by lucky01001** [comment]
hey @ZiJace  thanks for your answer! So can I safely run the tests with the power supply instead of the batteries?

**Comment by ZiJace** [comment]
@lucky01001 No, the battery must be installed for testing.The data line power supply can only let raspberry pi work.

**Comment by DenzelChen** [comment]
@lustoerk I am very sorry that we did not check the issues on GitHub. It has been so long since your last comment. If there is anything we can do, please feel free to contact us via support@freenove.com
