### ISSUE TITLE
Charging

### ISSUE THREAD

**Issue by ManagerCat** [Freenove/Freenove_4WD_Smart_Car_Kit_for_Raspberry_Pi#13]
As far as I know, I can not charge the board by itself. I have to remove the batteries and charge them separately. Is there a way I can charge while the batteries are connected to the board and if not, is there an easier way to remove the batteries?

**Comment by DenzelChen** [comment]
Sorry. The board cannot charge the batteries.
1, You can put a wire in the battery holder when you install batteries. Then pull the wire to remove the batteries.
https://www.amazon.com/clouddrive/share/OOGXMq5Z6Af0UOg8aKra9oSynXpBRWKRTImLqW4WG3x

2, You can use a slot type screwdriver to remove the batteries.
https://www.amazon.com/clouddrive/share/JKQiWoVPM2oRP2pFNdKAN5etMVDA9KztlL6RQgxiRpA
