### ISSUE TITLE
Rasberry pi not switching on with batteries

### ISSUE THREAD

**Issue by suhasshastry** [Freenove/Freenove_4WD_Smart_Car_Kit_for_Raspberry_Pi#27]
I accidentally connected the raspberry pi to the power supply when it was mounted onto the car. Now the raspberry pi won't start with the batteries from the car. Did I damage the 4wd car circuit? Power seems to be not flowing into the pi.

PS: Rasberry pi is fine with a direct power connection.

**Comment by MallocArray** [comment]
You are using both power switches on the robot board, right?

**Comment by suhasshastry** [comment]
Yeah. both the switches. The green light of pi is never turned on.

**Comment by DenzelChen** [comment]
Please fully charge your batteries to try again.

**Comment by suhasshastry** [comment]
One of the batteries is not withstanding the charge. I will try with new batteries.

**Comment by suhasshastry** [comment]
One of the batteries was fried. Working fine with new batteries. Thanks @DenzelChen
