### ISSUE TITLE
Checking if data2==None twice

### ISSUE THREAD

**Issue by HarHarLinks** [Freenove/Freenove_4WD_Smart_Car_Kit_for_Raspberry_Pi#42]
https://github.com/Freenove/Freenove_4WD_Smart_Car_Kit_for_Raspberry_Pi/blob/4c513154fb11cae7d11f924c7c11688daf611bd4/Code/Server/server.py#L197

https://github.com/Freenove/Freenove_4WD_Smart_Car_Kit_for_Raspberry_Pi/blob/4c513154fb11cae7d11f924c7c11688daf611bd4/Code/Server/server.py#L218

1. data2 is checked twice.
2. data4 is never checked. is this intentional?
3. there are at least these 2 occurrences.
4. please use `is None` instead of `== None` per PEP8 (https://www.flake8rules.com/rules/E711.html)

**Comment by fire-eggs** [comment]
Wow! Thank you for this, somehow I never noticed!

**Comment by fire-eggs** [comment]
[Finally addressed](https://github.com/Freenove/Freenove_4WD_Smart_Car_Kit_for_Raspberry_Pi/commit/271306cc2855256e1575956d72783bda2f066321).
