### ISSUE TITLE
Test.py

### ISSUE THREAD

**Issue by buzz2246** [Freenove/Freenove_4WD_Smart_Car_Kit_for_Raspberry_Pi#5]
so I got to testing test ing the motor and it will not work it keeps saying
File "test.py", line 2
    from Led import 
                   ^
SyntaxError: invalid syntax
and so can some one tell me what is happening

**Comment by buzz2246** [comment]
so I just did the other test to and they are also not working they say the samething

**Comment by DenzelChen** [comment]
@buzz2246 Could you please contact us via support@freenove.com with pictures? Thank you.
