### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by kevkid** [Freenove/Freenove_4WD_Smart_Car_Kit_for_Raspberry_Pi#7]
I am looking through the code to see how video is being transmitted. It looks like you are using picamera to rapidly capture small jpg images and transmit them over udp (I believe its udp according to the server code `s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)`). I am curious if this can be replaced with something faster like a direct h264 stream. My assumption is that I can use something like gstreamer to capture the video and stream it quickly. 

My question: Where is the code that displays the video in the ui? I am having difficulty finding it.

**Comment by DenzelChen** [comment]
The code is in main.py
![20200908142115](https://user-images.githubusercontent.com/22834809/92440172-ab77a480-f1de-11ea-91cc-18682015b7b4.png)

Display the image through a label control. Of course you can also transmit video via HTTP protocol.
