### ISSUE TITLE
Just beeps while running server

### ISSUE THREAD

**Issue by ChopsKingsland** [Freenove/Freenove_4WD_Smart_Car_Kit_for_Raspberry_Pi#8]
I am trying to run the server code, but when its run, it just beeps and won't stop even when i connect to it... any ideas?

**Comment by DenzelChen** [comment]
Dear customer, please check if batteries are fully charged. And please contact support@freenove.com for further support. Thank you.

**Comment by clemens-k** [comment]
@ChopsKingsland If the problem was solved, please close this issue.
